# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Tom's Github settings
# title: Calm Meditation
# baseurl: /calm-meditation
# url: http://idratherbewriting.com
# baseurl_media: http://idratherassets.com/calm-meditation/
# github_username:  tomjohnson1492
# author: Tom Johnson
# email: tom@idratherbewriting.com

# Amazon AWS settings

title: Movieland
email: wajid_bux@yahoo.com
#baseurl: /movieland
url: https://movieland.netlify.app
#baseurl_media: /
#github_username:  amzn-tomjoht
author: Movieland
logo: movieland_logo_small.png
#copyright_license:
copyright_url: https://creativecommons.org/licenses/by/4.0/

logo: movieland_logo_small.png
theme: minima
# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

description: >
  Movieland offers a break from your regular streaming routine. 
  This channel provides Classic Movies from the golden age of Hollywood. 
  Watch action, comedy, drama, horror, film noir and documentary movies
  featuring all-time greats like Cary Grant, Elizabeth Taylor, James Stewart, Bob Hope, John Wayne.